# Generated by Django 3.0.4 on 2022-07-09 02:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(default=0)),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('Brain', '脳神経'), ('Respiratory', '呼吸器'), ('Circulation', '循環器'), ('Digestive', '消化器'), ('Kidney_Urology', '腎・泌尿器'), ('Endocrine_metabolism_nutrition', '内分泌・代謝・栄養'), ('Orthopedics', '整形外科'), ('Hematology', '血液'), ('Ophthalmology', '眼科'), ('Dermatology', '皮膚科'), ('Otorhinolaryngology', '耳鼻咽喉科'), ('Dental', '歯科口腔外科'), ('Obstetrics', '産婦人科'), ('Psychiatry', '精神科'), ('Firstaid_icu', '救急・ICU'), ('Others', 'その他')], max_length=50)),
                ('category', models.CharField(choices=[('Pathology', '病態'), ('Symptoms', '症状'), ('Clinical_examination', '検査'), ('Image_inspection', '画像'), ('Diagnose', '診断'), ('Treatment', '治療'), ('Nurse', '看護'), ('Free_item', 'フリー項目')], max_length=50)),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
            ],
        ),
    ]
